---
- name: Install podman
  become: true
  package:
    name:
      - podman
    state: present

# - name: Pull latest virt image of kraken-layercake
#   become: true
#   containers.podman.podman_image:
#     name: docker.io/krakenhpc/kraken-layercake
#     tag: '{{ "virt-latest" if kr_with_vbox else "latest" }}'

- name: Write the kraken runtime configuration file
  become: true
  shell:
    cmd: >
      podman run docker.io/krakenhpc/kraken-layercake:{{ "virt-latest" if kr_with_vbox else "latest" }} 
      -printrc 
      -id "{{ kraken_id }}" 
      -ip "{{ kraken_ip }}" 
      -ipapi "{{ kraken_ipapi }}" 
      -log "{{ kraken_loglevel }}" 
      -state "{{ kraken_state_file }}" 
      > /etc/kraken/{{ "layercake-virt" if kr_with_vbox else "layercake" }}/config.yaml
      && touch /etc/kraken/.ansible_config
    creates: /etc/kraken/.ansible_config

- name: Create Kraken container
  become: true
  register: container_output
  containers.podman.podman_container:
    name: '{{ "kraken-layercake-virt" if kr_with_vbox else "kraken-layercake" }}'
    image: 'docker.io/krakenhpc/kraken-layercake:{{ "virt-latest" if kr_with_vbox else "latest" }}'
    state: created
    volume:
      - /home/vagrant/tftp:/tftp
      - /etc/kraken:/etc/kraken
    network: host
    # cmd_args: --sdnotify=container
    command:
      - -config
      - /etc/kraken/{{ "layercake-virt" if kr_with_vbox else "layercake" }}/config.yaml
      - -sdnotify
      - -noprefix

# - set_fact:
#     container_id={{ container_output.stdout }}

- debug:
    msg: "container_output =  {{ container_output }}"

- debug:
    msg: "container_output =  {{ container_output.container.Id }}"

- set_fact: container_id={{ container_output.container.Id }}
