---
# build with vbox?
kr_with_vbox: true
# build rpm instead of direct compilation?
kr_rpm: true
# when building rpm, include initramfs?
kr_rpm_with_initramfs: false
# `.<dist>.x86_64.rpm`, e.g. "el8"
kr_rpm_dist: el8
kr_rpm_working_dir: /home/vagrant

### FIXME - we should be able to derive versions from spec file
# version of kraken/layercake build
kr_version: 0.1.0
# release of kraken/layercake build, e.g. 0.1.0-rc1
kr_release: "rc1"

### Computed values
kr_rpm_path: "{{ ansible_env.HOME }}/rpmbuild/RPMS/x86_64/\
  kraken-layercake-{{ 'vbox-' if kr_with_vbox else '' }}\
  {{ kr_version }}-{{ kr_release }}\
  .{{ kr_rpm_dist}}.x86_64.rpm"
kr_target: "{{ 'kraken-layercake-vbox' if kr_vbox else 'kraken-layercake'}}"
